// Generated by gencpp from file face_detector/FaceDetectorGoal.msg
// DO NOT EDIT!


#ifndef FACE_DETECTOR_MESSAGE_FACEDETECTORGOAL_H
#define FACE_DETECTOR_MESSAGE_FACEDETECTORGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace face_detector
{
template <class ContainerAllocator>
struct FaceDetectorGoal_
{
  typedef FaceDetectorGoal_<ContainerAllocator> Type;

  FaceDetectorGoal_()
    {
    }
  FaceDetectorGoal_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::face_detector::FaceDetectorGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_detector::FaceDetectorGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FaceDetectorGoal_

typedef ::face_detector::FaceDetectorGoal_<std::allocator<void> > FaceDetectorGoal;

typedef boost::shared_ptr< ::face_detector::FaceDetectorGoal > FaceDetectorGoalPtr;
typedef boost::shared_ptr< ::face_detector::FaceDetectorGoal const> FaceDetectorGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::face_detector::FaceDetectorGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace face_detector

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::face_detector::FaceDetectorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::face_detector::FaceDetectorGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::face_detector::FaceDetectorGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::face_detector::FaceDetectorGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_detector/FaceDetectorGoal";
  }

  static const char* value(const ::face_detector::FaceDetectorGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal\n"
;
  }

  static const char* value(const ::face_detector::FaceDetectorGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaceDetectorGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_detector::FaceDetectorGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::face_detector::FaceDetectorGoal_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FACE_DETECTOR_MESSAGE_FACEDETECTORGOAL_H
