// Generated by gencpp from file burger_move_action/Burger_moveResult.msg
// DO NOT EDIT!


#ifndef BURGER_MOVE_ACTION_MESSAGE_BURGER_MOVERESULT_H
#define BURGER_MOVE_ACTION_MESSAGE_BURGER_MOVERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace burger_move_action
{
template <class ContainerAllocator>
struct Burger_moveResult_
{
  typedef Burger_moveResult_<ContainerAllocator> Type;

  Burger_moveResult_()
    : current_distance(0)
    , status()
    , request_id(0)  {
    }
  Burger_moveResult_(const ContainerAllocator& _alloc)
    : current_distance(0)
    , status(_alloc)
    , request_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _current_distance_type;
  _current_distance_type current_distance;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef int32_t _request_id_type;
  _request_id_type request_id;





  typedef boost::shared_ptr< ::burger_move_action::Burger_moveResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::burger_move_action::Burger_moveResult_<ContainerAllocator> const> ConstPtr;

}; // struct Burger_moveResult_

typedef ::burger_move_action::Burger_moveResult_<std::allocator<void> > Burger_moveResult;

typedef boost::shared_ptr< ::burger_move_action::Burger_moveResult > Burger_moveResultPtr;
typedef boost::shared_ptr< ::burger_move_action::Burger_moveResult const> Burger_moveResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::burger_move_action::Burger_moveResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::burger_move_action::Burger_moveResult_<ContainerAllocator1> & lhs, const ::burger_move_action::Burger_moveResult_<ContainerAllocator2> & rhs)
{
  return lhs.current_distance == rhs.current_distance &&
    lhs.status == rhs.status &&
    lhs.request_id == rhs.request_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::burger_move_action::Burger_moveResult_<ContainerAllocator1> & lhs, const ::burger_move_action::Burger_moveResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace burger_move_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::burger_move_action::Burger_moveResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::burger_move_action::Burger_moveResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::burger_move_action::Burger_moveResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9437765222ca81189f828d9e84428a38";
  }

  static const char* value(const ::burger_move_action::Burger_moveResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9437765222ca8118ULL;
  static const uint64_t static_value2 = 0x9f828d9e84428a38ULL;
};

template<class ContainerAllocator>
struct DataType< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "burger_move_action/Burger_moveResult";
  }

  static const char* value(const ::burger_move_action::Burger_moveResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"int32 current_distance\n"
"string status\n"
"int32 request_id\n"
;
  }

  static const char* value(const ::burger_move_action::Burger_moveResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_distance);
      stream.next(m.status);
      stream.next(m.request_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Burger_moveResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::burger_move_action::Burger_moveResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::burger_move_action::Burger_moveResult_<ContainerAllocator>& v)
  {
    s << indent << "current_distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.current_distance);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "request_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.request_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BURGER_MOVE_ACTION_MESSAGE_BURGER_MOVERESULT_H
