// Auto-generated. Do not edit!

// (in-package burger_move_action.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class Burger_moveResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_distance = null;
      this.status = null;
      this.request_id = null;
    }
    else {
      if (initObj.hasOwnProperty('current_distance')) {
        this.current_distance = initObj.current_distance
      }
      else {
        this.current_distance = 0;
      }
      if (initObj.hasOwnProperty('status')) {
        this.status = initObj.status
      }
      else {
        this.status = '';
      }
      if (initObj.hasOwnProperty('request_id')) {
        this.request_id = initObj.request_id
      }
      else {
        this.request_id = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type Burger_moveResult
    // Serialize message field [current_distance]
    bufferOffset = _serializer.int32(obj.current_distance, buffer, bufferOffset);
    // Serialize message field [status]
    bufferOffset = _serializer.string(obj.status, buffer, bufferOffset);
    // Serialize message field [request_id]
    bufferOffset = _serializer.int32(obj.request_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type Burger_moveResult
    let len;
    let data = new Burger_moveResult(null);
    // Deserialize message field [current_distance]
    data.current_distance = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [status]
    data.status = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [request_id]
    data.request_id = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.status);
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'burger_move_action/Burger_moveResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9437765222ca81189f828d9e84428a38';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    int32 current_distance
    string status
    int32 request_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new Burger_moveResult(null);
    if (msg.current_distance !== undefined) {
      resolved.current_distance = msg.current_distance;
    }
    else {
      resolved.current_distance = 0
    }

    if (msg.status !== undefined) {
      resolved.status = msg.status;
    }
    else {
      resolved.status = ''
    }

    if (msg.request_id !== undefined) {
      resolved.request_id = msg.request_id;
    }
    else {
      resolved.request_id = 0
    }

    return resolved;
    }
};

module.exports = Burger_moveResult;
